version: '3.8'

services:
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stackoverflow
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ../stackoverflow-spring
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/stackoverflow
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ../frontend-angular
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mysql-data:
